<?php

declare(strict_types=1);

namespace LexiconSyntax\Generator;

use LexiconSyntax\Model\GrammarModel;
use LexiconSyntax\Model\NodeModel;
use LexiconSyntax\Typing\ArrayType;
use LexiconSyntax\Typing\NamedType;
use LexiconSyntax\Typing\NodeNameType;
use LexiconSyntax\Typing\RuleNameType;
use LexiconSyntax\Typing\SemanticTypeInterface;
use LexiconSyntax\Typing\TokenNameType;
use LexiconSyntax\Typing\UnionType;
use RuntimeException;

final readonly class AstNodeGenerator
{
    private const NAMESPACE = 'Generated\Ast';

    /**
     * @return list<string>
     */
    public static function generate(GrammarModel $model, string $outputDirectory): array
    {
        self::ensureDirectory($outputDirectory);

        $written = [];
        $parentNames = self::parentNames($model);
        foreach ($model->nodes as $node) {
            $className = self::className($node->name);
            $path = $outputDirectory . DIRECTORY_SEPARATOR . $className . '.php';
            file_put_contents($path, self::nodeSource($className, $node, $model, $parentNames));
            $written[] = $path;
        }

        return $written;
    }

    /**
     * @param array<string, true> $parentNames
     */
    private static function nodeSource(string $className, NodeModel $node, GrammarModel $model, array $parentNames): string
    {
        if (isset($parentNames[$node->name])) {
            return self::interfaceSource($className);
        }

        return self::classSource($className, $node, $model);
    }

    private static function interfaceSource(string $className): string
    {
        return implode(PHP_EOL, [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace ' . self::NAMESPACE . ';',
            '',
            '// Generated by Lexicon Syntax. Do not edit by hand.',
            'interface ' . $className,
            '{',
            '}',
            '',
        ]);
    }

    private static function classSource(string $className, NodeModel $node, GrammarModel $model): string
    {
        $usesToken = false;
        $properties = [];

        foreach ($node->fields as $field) {
            $type = self::phpType($field->type, $model);
            $usesToken = $usesToken || str_contains($type, 'Token');
            $properties[] = ['name' => $field->name, 'type' => $type];
        }

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace ' . self::NAMESPACE . ';',
            '',
        ];

        if ($usesToken) {
            $lines[] = 'use Lexicon\Lexer\Token;';
            $lines[] = '';
        }

        $lines[] = '// Generated by Lexicon Syntax. Do not edit by hand.';
        $implements = $node->parentName === null ? '' : ' implements ' . self::className($node->parentName);
        $lines[] = 'final readonly class ' . $className . $implements;
        $lines[] = '{';

        if ($properties === []) {
            $lines[] = '}';
            $lines[] = '';

            return implode(PHP_EOL, $lines);
        }

        $lines[] = '    public function __construct(';
        foreach ($properties as $index => $property) {
            $suffix = $index === array_key_last($properties) ? '' : ',';
            $lines[] = sprintf('        public %s $%s%s', $property['type'], $property['name'], $suffix);
        }

        $lines[] = '    ) {';
        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }

    /**
     * @param array<string, true> $seenRules
     */
    private static function phpType(SemanticTypeInterface $type, GrammarModel $model, array $seenRules = []): string
    {
        if ($type instanceof ArrayType) {
            return 'array';
        }

        if ($type instanceof TokenNameType) {
            return 'Token';
        }

        if ($type instanceof NodeNameType) {
            return self::className($type->name);
        }

        if ($type instanceof RuleNameType) {
            if (isset($seenRules[$type->name]) || !isset($model->rules[$type->name])) {
                return 'mixed';
            }

            return self::phpType($model->rules[$type->name]->returnType, $model, $seenRules + [$type->name => true]);
        }

        if ($type instanceof NamedType) {
            return match ($type->name) {
                'token' => 'Token',
                'rule' => 'mixed',
                default => 'mixed',
            };
        }

        if ($type instanceof UnionType) {
            return self::unionPhpType($type, $model, $seenRules);
        }

        return 'mixed';
    }

    /**
     * @param array<string, true> $seenRules
     */
    private static function unionPhpType(UnionType $type, GrammarModel $model, array $seenRules): string
    {
        $types = array_values(array_unique(array_map(
            fn (SemanticTypeInterface $candidate): string => self::phpType($candidate, $model, $seenRules),
            $type->types
        )));

        sort($types);

        if ($types === ['Token']) {
            return 'Token';
        }

        if (count($types) > 1 && !in_array('mixed', $types, true) && !in_array('array', $types, true)) {
            return implode('|', $types);
        }

        return 'mixed';
    }

    /**
     * @return array<string, true>
     */
    private static function parentNames(GrammarModel $model): array
    {
        $parents = [];
        foreach ($model->nodes as $node) {
            if ($node->parentName !== null) {
                $parents[$node->parentName] = true;
            }
        }

        return $parents;
    }

    private static function className(string $name): string
    {
        $className = str_ends_with($name, 'Node') ? $name : $name . 'Node';
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $className) !== 1) {
            throw new RuntimeException(sprintf("Invalid generated AST class name '%s'.", $className));
        }

        return $className;
    }

    private static function ensureDirectory(string $directory): void
    {
        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException(sprintf("Directory '%s' could not be created.", $directory));
        }
    }
}
