<?php

declare(strict_types=1);

namespace LexiconSyntax\Generator;

use LexiconSyntax\Planning\Parser\Expression\ChoiceExpression;
use LexiconSyntax\Planning\Parser\Expression\ArrayPrependExpression;
use LexiconSyntax\Planning\Parser\Expression\ArrayExpression;
use LexiconSyntax\Planning\Parser\Expression\ConstructNodeExpression;
use LexiconSyntax\Planning\Parser\Expression\FoldLeftExpression;
use LexiconSyntax\Planning\Parser\Expression\ManyExpression;
use LexiconSyntax\Planning\Parser\Expression\NullExpression;
use LexiconSyntax\Planning\Parser\Expression\OneOrMoreExpression;
use LexiconSyntax\Planning\Parser\Expression\OptionalExpression;
use LexiconSyntax\Planning\Parser\Expression\ParserExpressionInterface;
use LexiconSyntax\Planning\Parser\Expression\RuleCallExpression;
use LexiconSyntax\Planning\Parser\Expression\SequenceExpression;
use LexiconSyntax\Planning\Parser\Expression\SuccessExpression;
use LexiconSyntax\Planning\Parser\Expression\TokenMatchExpression;
use LexiconSyntax\Planning\Parser\Expression\VariableExpression;
use LexiconSyntax\Planning\Parser\ParserMethodPlan;
use LexiconSyntax\Planning\Parser\ParserPlan;
use LexiconSyntax\Planning\Parser\Statement\AssignStatement;
use LexiconSyntax\Planning\Parser\Statement\ParserStatementInterface;
use LexiconSyntax\Planning\Parser\Statement\ReturnNullOnNullStatement;
use LexiconSyntax\Planning\Parser\Statement\SavePositionStatement;
use RuntimeException;

final readonly class RecursiveParserGenerator
{
    private const NAMESPACE = 'Generated';

    /**
     * @return list<string>
     */
    public static function generate(ParserPlan $plan, string $outputDirectory): array
    {
        self::ensureDirectory($outputDirectory);

        $path = $outputDirectory . DIRECTORY_SEPARATOR . $plan->name . '.php';
        file_put_contents($path, self::parserSource($plan));

        return [$path];
    }

    private static function parserSource(ParserPlan $plan): string
    {
        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace ' . self::NAMESPACE . ';',
            '',
            'use Lexicon\Lexer\Token;',
            'use Lexicon\Parser\TokenStream;',
            'use RuntimeException;',
            '',
            '// Generated by Lexicon Syntax. Do not edit by hand.',
            'final class ' . $plan->name,
            '{',
            '    private TokenStream $tokens;',
            '',
            '    /**',
            '     * @param non-empty-list<Token> $tokens',
            '     */',
            '    public function __construct(array $tokens)',
            '    {',
            '        $this->tokens = new TokenStream($tokens);',
            '    }',
            '',
            '    public function parse(): mixed',
            '    {',
            '        return $this->required($this->' . $plan->startMethodName . '(), ' . var_export('Expected ' . $plan->startRuleName . '.', true) . ');',
            '    }',
        ];

        foreach ($plan->methods as $method) {
            $lines[] = '';
            $lines = [...$lines, ...self::method($method, $plan)];
        }

        return implode(PHP_EOL, [
            ...$lines,
            '',
            '    private function required(mixed $value, string $message): mixed',
            '    {',
            '        if ($value !== null) {',
            '            return $value;',
            '        }',
            '',
            '        throw new RuntimeException($message);',
            '    }',
            '}',
            '',
        ]);
    }

    /**
     * @return list<string>
     */
    private static function method(ParserMethodPlan $method, ParserPlan $plan): array
    {
        $lines = [
            '    private function ' . $method->name . '(): mixed',
            '    {',
        ];

        foreach ($method->statements as $statement) {
            $lines = [...$lines, ...self::statement($statement, $plan)];
        }

        if ($method->statements !== []) {
            $lines[] = '';
        }

        $lines[] = '        return ' . self::expression($method->returnExpression, $plan) . ';';
        $lines[] = '    }';

        return $lines;
    }

    /**
     * @return list<string>
     */
    private static function statement(ParserStatementInterface $statement, ParserPlan $plan): array
    {
        if ($statement instanceof SavePositionStatement) {
            return ['        $position = $this->tokens->save();'];
        }

        if ($statement instanceof AssignStatement) {
            return ['        $' . $statement->variable . ' = ' . self::expression($statement->expression, $plan) . ';'];
        }

        if ($statement instanceof ReturnNullOnNullStatement) {
            return [
                '        if ($' . $statement->variable . ' === null) {',
                '            $this->tokens->restore($position);',
                '            return null;',
                '        }',
            ];
        }

        throw new RuntimeException(sprintf('Statement %s is not supported by PHP parser generation yet.', $statement::class));
    }

    private static function expression(ParserExpressionInterface $expression, ParserPlan $plan): string
    {
        if ($expression instanceof TokenMatchExpression) {
            return '$this->tokens->match(' . $plan->tokenEnumName . '::' . $expression->tokenName . ')';
        }

        if ($expression instanceof RuleCallExpression) {
            return '$this->' . $expression->methodName . '()';
        }

        if ($expression instanceof ChoiceExpression) {
            $choices = array_map(
                fn (ParserExpressionInterface $choice): string => self::choice($choice, $plan),
                $expression->choices
            );

            if (count($choices) === 1 || !self::hasMultilineChoice($choices)) {
                return '$this->tokens->oneOf(' . implode(', ', $choices) . ')';
            }

            return '$this->tokens->oneOf(' . PHP_EOL
                . '            ' . implode(',' . PHP_EOL . '            ', $choices) . PHP_EOL
                . '        )';
        }

        if ($expression instanceof OptionalExpression) {
            return '$this->tokens->optional(' . self::choice($expression->expression, $plan) . ')';
        }

        if ($expression instanceof ManyExpression) {
            return '$this->tokens->many(' . self::choice($expression->expression, $plan) . ')';
        }

        if ($expression instanceof OneOrMoreExpression) {
            return '$this->tokens->oneOrMore(' . self::choice($expression->expression, $plan) . ')';
        }

        if ($expression instanceof ConstructNodeExpression) {
            return 'new Ast\\' . self::nodeClassName($expression->nodeName) . '(' . implode(', ', array_map(
                fn (string $argument): string => self::expression(new VariableExpression($argument), $plan),
                $expression->arguments
            )) . ')';
        }

        if ($expression instanceof VariableExpression) {
            return '$' . $expression->name;
        }

        if ($expression instanceof ArrayPrependExpression) {
            return 'array_merge([' . self::expression($expression->head, $plan) . '], ' . self::expression($expression->tail, $plan) . ')';
        }

        if ($expression instanceof ArrayExpression) {
            return '[' . implode(', ', array_map(
                fn (ParserExpressionInterface $item): string => self::expression($item, $plan),
                $expression->items
            )) . ']';
        }

        if ($expression instanceof FoldLeftExpression) {
            return '(function (mixed $node, array $items): mixed {' . PHP_EOL
                . '            foreach ($items as $item) {' . PHP_EOL
                . '                $node = new Ast\\' . self::nodeClassName($expression->nodeName) . '($node, $item[0], $item[1]);' . PHP_EOL
                . '            }' . PHP_EOL
                . PHP_EOL
                . '            return $node;' . PHP_EOL
                . '        })(' . self::expression($expression->head, $plan) . ', ' . self::expression($expression->tail, $plan) . ')';
        }

        if ($expression instanceof SuccessExpression) {
            return 'true';
        }

        if ($expression instanceof NullExpression) {
            return 'null';
        }

        if ($expression instanceof SequenceExpression) {
            return self::sequenceCall($expression, $plan);
        }

        throw new RuntimeException(sprintf('Expression %s is not supported by PHP parser generation yet.', $expression::class));
    }

    private static function choice(ParserExpressionInterface $expression, ParserPlan $plan): string
    {
        if ($expression instanceof TokenMatchExpression) {
            return $plan->tokenEnumName . '::' . $expression->tokenName;
        }

        if ($expression instanceof RuleCallExpression) {
            return 'fn (): mixed => $this->' . $expression->methodName . '()';
        }

        if ($expression instanceof SequenceExpression) {
            return self::sequenceChoice($expression, $plan);
        }

        throw new RuntimeException(sprintf('Choice expression %s is not supported by PHP parser generation yet.', $expression::class));
    }

    private static function sequenceChoice(SequenceExpression $expression, ParserPlan $plan): string
    {
        $captures = self::assignedVariables($expression);
        $use = $captures === [] ? '' : ' use (' . implode(', ', array_map(
            fn (string $variable): string => '&$' . $variable,
            $captures
        )) . ')';

        $lines = ['fn (): mixed => (function ()' . $use . ': mixed {'];
        foreach ($expression->statements as $statement) {
            foreach (self::statement($statement, $plan) as $line) {
                $lines[] = self::closureLine($line);
            }
        }

        $lines[] = '';
        $lines[] = '    return ' . self::expression($expression->returnExpression, $plan) . ';';
        $lines[] = '})()';

        return implode(PHP_EOL . '            ', $lines);
    }

    private static function sequenceCall(SequenceExpression $expression, ParserPlan $plan): string
    {
        $lines = ['(function (): mixed {'];
        foreach ($expression->statements as $statement) {
            foreach (self::statement($statement, $plan) as $line) {
                $lines[] = self::closureLine($line);
            }
        }

        $lines[] = '';
        $lines[] = '    return ' . self::expression($expression->returnExpression, $plan) . ';';
        $lines[] = '})()';

        return implode(PHP_EOL . '        ', $lines);
    }

    /**
     * @return list<string>
     */
    private static function assignedVariables(SequenceExpression $expression): array
    {
        $variables = [];
        foreach ($expression->statements as $statement) {
            if ($statement instanceof AssignStatement && $statement->variable !== 'result') {
                $variables[] = $statement->variable;
            }
        }

        return array_values(array_unique($variables));
    }

    /**
     * @param list<string> $choices
     */
    private static function hasMultilineChoice(array $choices): bool
    {
        foreach ($choices as $choice) {
            if (str_contains($choice, PHP_EOL)) {
                return true;
            }
        }

        return false;
    }

    private static function closureLine(string $line): string
    {
        $relative = str_starts_with($line, '        ')
            ? substr($line, 8)
            : ltrim($line);

        return '    ' . $relative;
    }

    private static function nodeClassName(string $name): string
    {
        $className = str_ends_with($name, 'Node') ? $name : $name . 'Node';
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $className) !== 1) {
            throw new RuntimeException(sprintf("Invalid generated node class name '%s'.", $className));
        }

        return $className;
    }

    private static function ensureDirectory(string $directory): void
    {
        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException(sprintf("Directory '%s' could not be created.", $directory));
        }
    }
}
