<?php

declare(strict_types=1);

namespace LexiconSyntax\Generator;

use LexiconSyntax\Ast\CustomMatcherExpressionNode;
use LexiconSyntax\Ast\ExpressionNode;
use LexiconSyntax\Ast\ExpressionNodeInterface;
use LexiconSyntax\Ast\StringLiteralExpressionNode;
use LexiconSyntax\Ast\TokenDeclarationNode;
use LexiconSyntax\Model\GrammarModel;
use RuntimeException;

final readonly class TokenEnumGenerator
{
    private const NAMESPACE = 'Generated';

    private const BUILT_IN_MATCHERS = [
        'IdentifierMatcher' => 'Lexicon\Lexer\Matchers\IdentifierTokenMatcher',
        'NumberMatcher' => 'Lexicon\Lexer\Matchers\NumberTokenMatcher',
        'IntegerMatcher' => 'Lexicon\Lexer\Matchers\IntegerTokenMatcher',
        'DecimalMatcher' => 'Lexicon\Lexer\Matchers\DecimalTokenMatcher',
        'StringMatcher' => 'Lexicon\Lexer\Matchers\StringTokenMatcher',
        'JsonStringMatcher' => 'Lexicon\Lexer\Matchers\JsonStringTokenMatcher',
        'JsonNumberMatcher' => 'Lexicon\Lexer\Matchers\JsonNumberTokenMatcher',
        'WhitespaceMatcher' => 'Lexicon\Lexer\Matchers\WhitespaceTokenMatcher',
        'LineCommentMatcher' => 'Lexicon\Lexer\Matchers\LineCommentTokenMatcher',
        'BlockCommentMatcher' => 'Lexicon\Lexer\Matchers\BlockCommentTokenMatcher',
        'WordMatcher' => 'Lexicon\Lexer\Matchers\WordTokenMatcher',
        'CharacterMatcher' => 'Lexicon\Lexer\Matchers\CharacterTokenMatcher',
    ];

    /**
     * @return list<string>
     */
    public static function generate(GrammarModel $model, string $outputDirectory, string $enumName): array
    {
        self::ensureDirectory($outputDirectory);

        $matcherNames = [];
        $enumPath = $outputDirectory . DIRECTORY_SEPARATOR . $enumName . '.php';
        file_put_contents($enumPath, self::enumSource($model, $enumName, $matcherNames));

        $written = [$enumPath];
        if ($matcherNames !== []) {
            $matcherDirectory = $outputDirectory . DIRECTORY_SEPARATOR . 'Matcher';
            self::ensureDirectory($matcherDirectory);

            foreach (array_values(array_unique($matcherNames)) as $matcherName) {
                $path = $matcherDirectory . DIRECTORY_SEPARATOR . $matcherName . '.php';
                file_put_contents($path, self::matcherSource($matcherName));
                $written[] = $path;
            }
        }

        return $written;
    }

    /**
     * @param list<string> $matcherNames
     */
    private static function enumSource(GrammarModel $model, string $enumName, array &$matcherNames): string
    {
        $cases = [];
        $imports = [
            'Lexicon\Lexer\Attributes\EndOfFile',
            'Lexicon\Lexer\Attributes\Fixed',
            'Lexicon\Lexer\Attributes\Identifier',
            'Lexicon\Lexer\Attributes\Keyword',
            'Lexicon\Lexer\Attributes\Literal',
            'Lexicon\Lexer\Attributes\Symbol',
            'Lexicon\Lexer\Attributes\Trivia',
            'Lexicon\Lexer\Attributes\Unknown',
        ];

        foreach ($model->tokens as $token) {
            $attribute = self::tokenAttribute($token->category, $token->name, $token->expression, $matcherNames, $imports);
            $cases[] = '    ' . $attribute;
            $cases[] = '    case ' . $token->name . ';';
            $cases[] = '';
        }

        sort($imports);

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace ' . self::NAMESPACE . ';',
            '',
            ...array_map(fn (string $class): string => 'use ' . $class . ';', array_values(array_unique($imports))),
            '',
            '// Generated by Lexicon Syntax. Do not edit by hand.',
            'enum ' . $enumName,
            '{',
        ];

        if (end($cases) === '') {
            array_pop($cases);
        }

        $lines = [...$lines, ...$cases];
        $lines[] = '}';
        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }

    /**
     * @param list<string> $matcherNames
     * @param list<string> $imports
     */
    private static function tokenAttribute(
        ?string $category,
        string $name,
        ?ExpressionNodeInterface $expression,
        array &$matcherNames,
        array &$imports
    ): string
    {
        if ($category === 'eof') {
            return '#[EndOfFile]';
        }

        if ($category === 'unknown') {
            return '#[Unknown]';
        }

        $expression = self::unwrap($expression);

        if ($expression instanceof StringLiteralExpressionNode) {
            $text = self::stringValue($expression->literal->token->value);

            return match ($category) {
                'keyword' => '#[Keyword(' . var_export($text, true) . ')]',
                'symbol' => '#[Symbol(' . var_export($text, true) . ')]',
                default => '#[Fixed(' . var_export($text, true) . ')]',
            };
        }

        if ($expression instanceof CustomMatcherExpressionNode) {
            $matcherName = self::className($expression->name->token->value);
            $matcherClass = self::matcherClass($matcherName, $matcherNames, $imports);

            return match ($category) {
                'trivia' => '#[Trivia(' . $matcherClass . ')]',
                default => $name === 'Identifier'
                    ? '#[Identifier(' . $matcherClass . ')]'
                    : '#[Literal(' . $matcherClass . ')]',
            };
        }

        throw new RuntimeException(sprintf("Token '%s' uses an unsupported expression for token enum generation.", $name));
    }

    /**
     * @param list<string> $matcherNames
     * @param list<string> $imports
     */
    private static function matcherClass(string $matcherName, array &$matcherNames, array &$imports): string
    {
        $builtIn = self::BUILT_IN_MATCHERS[$matcherName] ?? null;
        if ($builtIn !== null) {
            $imports[] = $builtIn;

            return self::shortClassName($builtIn) . '::class';
        }

        $matcherNames[] = $matcherName;

        return 'Matcher\\' . $matcherName . '::class';
    }

    private static function unwrap(?ExpressionNodeInterface $expression): ?ExpressionNodeInterface
    {
        return $expression instanceof ExpressionNode ? $expression->inner : $expression;
    }

    private static function stringValue(string $quoted): string
    {
        return stripcslashes(substr($quoted, 1, -1));
    }

    private static function matcherSource(string $matcherName): string
    {
        return implode(PHP_EOL, [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace ' . self::NAMESPACE . '\Matcher;',
            '',
            'use Lexicon\Lexer\Lexer;',
            'use Lexicon\Lexer\Matchers\TokenMatcherInterface;',
            'use Lexicon\Lexer\Token;',
            '',
            '// Generated matcher stub. Fill in matching logic for this token.',
            'final class ' . $matcherName . ' implements TokenMatcherInterface',
            '{',
            '    public function match(Lexer $lexer): ?Token',
            '    {',
            '        return null;',
            '    }',
            '}',
            '',
        ]);
    }

    private static function ensureDirectory(string $directory): void
    {
        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException(sprintf("Directory '%s' could not be created.", $directory));
        }
    }

    private static function className(string $name): string
    {
        $name = preg_replace('/[^A-Za-z0-9_]/', '', $name) ?? '';
        if ($name === '' || preg_match('/^[A-Za-z_]/', $name) !== 1) {
            throw new RuntimeException(sprintf("Invalid matcher class name '%s'.", $name));
        }

        return $name;
    }

    private static function shortClassName(string $class): string
    {
        $parts = explode('\\', $class);

        return end($parts) ?: $class;
    }
}
